var response = [{"name":"Wild Ginger","short_description":"Chinese/Asian bistro with a vegetarian menu and labeled vegan options","price_range":"$$ - average","veg_level_description":"Vegan-Friendly","website":"http://www.wildginger.net","phone":"206-623-4450","address":"1401 Third Avenue, Seattle, WA 98101","images":[]}
,{"name":"Cyber Dogs","short_description":"Veggie hot dogs, espresso, and internet cafe","price_range":"$ - inexpensive","veg_level_description":"Vegetarian","phone":"206-405-DOGS","address":"909 Pike Street, Seattle, Washington 98101","images":[]}
,{"name":"Elliott Bay Cafe in Pioneer Square","short_description":"Cafe downstairs from Elliott Bay Books with vegan pastries","price_range":"$$ - average","veg_level_description":"Vegan-Friendly","website":"http://www.elliottbaybook.com","phone":"(206) 625-1600","address":"101 S. Main Street, Seattle, Washington 98104","images":["http://www.vegguide.org/entry-images/1175/1175-156-mini.gif","http://www.vegguide.org/entry-images/1175/1175-156-small.gif","http://www.vegguide.org/entry-images/1175/1175-156-large.gif","http://www.vegguide.org/entry-images/1175/1175-156-original.gif"]}
,{"name":"Juice It Cafe","short_description":"Hearty brown rice bowls, fresh juice & smoothie bar, salads.  Vegan & vegetarian options.","price_range":"$ - inexpensive","veg_level_description":"Vegan-Friendly","website":"http://juiceitcafe.com","phone":"206-447-6960","address":"825 Pike Street Washington State Convention Center, Seattle, WA 98101","images":[]}
,{"name":"Mexico Cantina y Veracruz Cooking","short_description":"Vegan Friendly Mexican Cuisine located in the Pacific Place Shopping Center","price_range":"$$ - average","veg_level_description":"Vegan-Friendly","website":"http://eatatmexico.com","phone":"206-405-3400","address":"600 Pine Street 4th Floor, Seattle, WA 98101","images":[]}
,{"name":"Cinnamon Works","short_description":"Bakery/Cafe","price_range":"$$ - average","veg_level_description":"Vegan-Friendly","website":"http://www.cinnamonworks.com","phone":"(206) 583-0085","address":"1536 Pike Place, Seattle, WA 98101","images":[]}
,{"name":"Gary's Tex-Mex Snack Shack","short_description":"Vegan-friendly Mexican foods in Pike Place Market","price_range":"$ - inexpensive","veg_level_description":"Vegan-Friendly","phone":"206-682-2243","address":"1514 Pike Place Suite 7, Seattle, WA 98101","images":[]}
,{"name":"Toi","short_description":"Thai restaurant and full bar in downtown Seattle","price_range":"$$ - average","veg_level_description":"Vegetarian-Friendly","website":"http://www.toiseattle.com","phone":"206-267-1017","address":"1904 4th Avenue, Seattle, Washington 89101","images":[]}
,{"name":"Uwajimaya Seattle","short_description":"Big Asian Market","price_range":"$$ - average","veg_level_description":"Vegan-Friendly","website":"http://www.uwajimaya.com/sea/index.html","address":"600 5th Avenue South, Seattle, Washington 98104","images":["http://www.vegguide.org/entry-images/4476/4476-2605-mini.jpg","http://www.vegguide.org/entry-images/4476/4476-2605-small.jpg","http://www.vegguide.org/entry-images/4476/4476-2605-large.jpg","http://www.vegguide.org/entry-images/4476/4476-2605-original.jpg"]}
,{"name":"FareStart","short_description":"Vegan-friendly sandwiches and more","price_range":"$ - inexpensive","veg_level_description":"Vegan-Friendly","website":"http://farestart.org","phone":"206-267-7601","address":"700 Virginia Street, Seattle, WA 98101","images":[]}
,{"name":"Travelers","short_description":"Indian food and grocery with large tea selection","price_range":"$ - inexpensive","veg_level_description":"Vegetarian","website":"http://www.travelersteaco.com","phone":"206-329-6260","address":"501 E. Pine St, Seattle, Washington 98122","images":[]}
,{"name":"Cafe Pettirosso","short_description":"Bistro with numerous, quality labeled vegan options","price_range":"$$ - average","veg_level_description":"Vegan-Friendly","website":"http://www.pettirossoseattle.com","phone":"206-324-2233","address":"1101 E Pike Street, Seattle, WA 98122","images":[]}
,{"name":"ChuMinh Tofu & Veggie Deli","short_description":"Vegetarian & Vietnamese Restaurant","price_range":"$ - inexpensive","veg_level_description":"Vegetarian","website":"http://www.yelp.com/biz/chuminh-tofu-and-veggie-deli-seattle","phone":"(206) 723-6095","address":"1043 S Jackson St (S 12th Ave & S 10th Ave), Seattle, Washington 98104","images":[]}
,{"name":"High 5 Pie","short_description":"Pie shop with two vegan options","price_range":"$ - inexpensive","veg_level_description":"Vegan-Friendly","website":"http://www.high5pie.com","phone":"(206) 695-2284","address":"1400 12th Avenue, Seattle, WA 98122","images":[]}
,{"name":"Molly Moon's Homemade Ice Cream","short_description":"Popular ice cream shop","price_range":"$ - inexpensive","veg_level_description":"Vegan-Friendly","website":"http://www.mollymoonicecream.com","phone":"206-708-7947","address":"917 E Pine St, Seattle, WA 98122","images":[]}
,{"name":"Action For Animals","short_description":"Vegan T-shirts, buttons, bumperstickers, books, activism, etc.","price_range":"$ - inexpensive","veg_level_description":"Not Veg-Friendly","website":"http://www.afa-online.org","phone":"206.227.5752","address":"PO BOX 45843, Seattle, Washington 98145","images":[]}
,{"name":"Amore Restaurant","short_description":"Italian food with labeled vegan options","price_range":"$$ - average","veg_level_description":"Vegan-Friendly","website":"http://www.tasteofamore.com","phone":"206-770-0606","address":"2301 5th Avenue, Seattle, WA 98121","images":[]}
,{"name":"Bluebird Homemade Ice Cream & Tea Room","short_description":"Tea and ice cream shop with vegan options","price_range":"$ - inexpensive","veg_level_description":"Vegan-Friendly","website":"http://bluebirdseattle.blogspot.com","address":"1205 E. Pike St., Seattle, WA 98122","images":[]}
,{"name":"D'Ambrosio","short_description":"Offers vegan gelato made with rice milk","price_range":"$ - inexpensive","veg_level_description":"Vegan-Friendly","website":"http://www.dambrosiogelato.com","address":"1542 12th Ave., Seattle, WA","images":[]}
,{"name":"In the Bowl","short_description":"Vegetarian Thai food","price_range":"$$ - average","veg_level_description":"Vegetarian","website":"http://www.inthebowlbistro.com","phone":"(206) 568-2343","address":"1554 E. Olive Way, Seattle, WA 98102","images":["http://www.vegguide.org/entry-images/4053/4053-2191-mini.jpg","http://www.vegguide.org/entry-images/4053/4053-2191-small.jpg","http://www.vegguide.org/entry-images/4053/4053-2191-large.jpg","http://www.vegguide.org/entry-images/4053/4053-2191-original.jpg"]}
,{"name":"Loving Hut","short_description":"Pan-Asian vegan food","price_range":"$ - inexpensive","veg_level_description":"Vegan","website":"http://lovinghut.us/seattle/","phone":"206-726-8669","address":"1226 South Jackson Street, Seattle, WA 98144","images":[]}
,{"name":"Plum Bistro","short_description":"Vegan bistro with cocktails and soul food","price_range":"$$$ - expensive","veg_level_description":"Vegan","website":"http://www.plumbistroseattle.com","phone":"206-838-5333","address":"1429 12th Avenue E, Seattle, WA 98122","images":[]}
,{"name":"Whole Foods Market","short_description":"One of the four Whole Foods Markets in the Seattle metro area!","price_range":"$$ - average","veg_level_description":"Vegan-Friendly","website":"http://www.wholefoodsmarket.com","phone":"206.621.9700","address":"2210 Westlake Ave, Seattle, Washington 98121","images":[]}
,{"name":"Bang Bang Cafe","short_description":"Coffee shop with vegan brunch foods, a famous mac and cheese, and more","price_range":"$ - inexpensive","veg_level_description":"Vegan-Friendly","website":"http://www.facebook.com/pages/Bang-Bang-Cafe-Seattle/173900138149","phone":"206-448-2233","address":"2460 Western Ave., Seattle, WA 98121","images":[]}
,{"name":"Healeo","short_description":"Health-oriented organic natural foods and products","price_range":"$ - inexpensive","veg_level_description":"Vegan-Friendly","website":"http://www.healeo.com","address":"15th Avenue and E. Madison St., Seattle, WA","images":[]}
,{"name":"Highline","short_description":"Vegan bar-restaurant from the owners of Squid & Ink","price_range":"$$ - average","veg_level_description":"Vegan","website":"http://highlineseattle.com","phone":"206-328-7837","address":"210 Broadway East, Seattle, WA 98102","images":[]}
,{"name":"Madison Market","short_description":"Community based natural foods store","price_range":"$$ - average","veg_level_description":"Vegan-Friendly","website":"http://www.madisonmarket.com","phone":"(206) 329-1545","address":" 1600 East Madison, Seattle, Washington","images":["http://www.vegguide.org/entry-images/1651/1651-559-mini.jpg","http://www.vegguide.org/entry-images/1651/1651-559-small.jpg","http://www.vegguide.org/entry-images/1651/1651-559-large.jpg","http://www.vegguide.org/entry-images/1651/1651-559-original.jpg"]}
,{"name":"Nollie's Cafe","short_description":"Cafe with vegan lasagna and baked goods","price_range":"$$ - average","veg_level_description":"Vegan-Friendly","website":"http://www.nolliescafe.com","phone":"206-402-6724","address":"1165 Harrison Street, Seattle, WA 98109","images":[]}
,{"name":"Portage Bay Cafe","short_description":"Local, organic, sustainable cafe","price_range":"$$ - average","veg_level_description":"Vegan-Friendly","website":"http://www.portagebaycafe.com","phone":"206-462-6400","address":"391 Terry Avenue N, Seattle, WA 98109","images":[]}
,{"name":"The Veggie Grill","short_description":"Fast, casual vegan food","price_range":"$$ - average","veg_level_description":"Vegan","website":"http://www.veggiegrill.com","phone":"206-623-0336","address":"446 Terry Avenue North, Seattle, WA 98109","images":[]}
,{"name":"Wedgwood II","short_description":"Vegetarian Thai food","price_range":"$ - inexpensive","veg_level_description":"Vegetarian","website":"http://www.wedgwoodii.com","phone":"(206) 724-0655","address":"420 Broadway East, Seattle, WA 98102","images":[]}
,{"name":"Moonlight","short_description":"veggie and non-veg Vietnamese","price_range":"$ - inexpensive","veg_level_description":"Vegan-Friendly","phone":"206-322-3378","address":"1919 S Jackson, Seattle, Washington","images":[]}
,{"name":"Central Cinema","short_description":"Movie theater and restaurant with vegan options","price_range":"$ - inexpensive","veg_level_description":"Vegan-Friendly","website":"http://www.central-cinema.com","phone":"206-328-3230","address":"1411 21st Avenue, Seattle, WA 98122","images":[]}
,{"name":"Rainbow Natural Grocery - Juice Bar","short_description":"Vegetarian Organic Juice Bar","price_range":"$$ - average","veg_level_description":"Vegetarian","phone":" (206) 329-8440","address":" 417 15th Ave. E, Seattle, Washington","images":[]}
,{"name":"Sage Cafe","short_description":"Vegan sandwich shop","price_range":"$$ - average","veg_level_description":"Vegan","website":"http://sagebakeryandcafe.com","phone":"(206) 325-6429","address":"324 15th Ave E., Seattle, Washington 98112","images":["http://www.vegguide.org/entry-images/2806/2806-1250-mini.jpg","http://www.vegguide.org/entry-images/2806/2806-1250-small.jpg","http://www.vegguide.org/entry-images/2806/2806-1250-large.jpg","http://www.vegguide.org/entry-images/2806/2806-1250-original.jpg"]}
,{"name":"Teapot Vegetarian House","short_description":"Vegan Asian cuisine, lots of faux meats.","price_range":"$ - inexpensive","veg_level_description":"Vegan","website":"http://www.teapotvegetarianhouse.com","phone":"206-325-1010","address":"345 15th Ave E, Seattle, Washington 98112","images":["http://www.vegguide.org/entry-images/243/243-1082-mini.jpg","http://www.vegguide.org/entry-images/243/243-1082-small.jpg","http://www.vegguide.org/entry-images/243/243-1082-large.jpg","http://www.vegguide.org/entry-images/243/243-1082-original.jpg"]}
,{"name":"The Neighbor Lady","short_description":"Bordello-themed bar with labeled vegan options","price_range":"$ - inexpensive","veg_level_description":"Vegan-Friendly","website":"https://www.facebook.com/pages/The-Neighbor-Lady/275156179191305?rf=202743139844489","phone":"(206) 235-0596","address":"2308 E. Union Street, Seattle, WA 98122","images":[]}
,{"name":"Bamboo Garden","short_description":"Chinese, faux meats","price_range":"$$ - average","veg_level_description":"Vegan","website":"http://www.bamboogarden.net","phone":"206-282-6616","address":"364 Roy St, Seattle, WA 98109","images":["http://www.vegguide.org/entry-images/237/237-1011-mini.jpg","http://www.vegguide.org/entry-images/237/237-1011-small.jpg","http://www.vegguide.org/entry-images/237/237-1011-large.jpg","http://www.vegguide.org/entry-images/237/237-1011-original.jpg"]}
,{"name":"Cortona Cafe","short_description":"Coffee shop with vegan baked goods","price_range":"$ - inexpensive","veg_level_description":"Vegan-Friendly","website":"http://www.cortonacafe.com","address":"2425 E. Union Street, Seattle, WA","images":[]}
,{"name":"Patty Pan Grill","short_description":"Grab and go Mexican vegetarian food","price_range":"$ - inexpensive","veg_level_description":"Vegan-Friendly","website":"http://pattypangrill.com","phone":"206-782-1558","address":"2310 E. Madison St., Seattle, Washington","images":[]}
,{"name":"Judkin's Street Cafe","short_description":"Simple American foods with vegan burgers, and a Meatless Monday menu","price_range":"$$ - average","veg_level_description":"Vegan-Friendly","website":"http://judkinsstreetcafe.com","phone":"206-322-1091","address":"2608 S. Judkins Street, Seattle, WA 98144","images":[]}
,{"name":"Cafe Flora","short_description":"International Gourmet Cusine","price_range":"$$$ - expensive","veg_level_description":"Vegetarian","website":"http://www.cafeflora.com","phone":"206-325-9100","address":"2901 E Madison St, Seattle, Washington 98112","images":["http://www.vegguide.org/entry-images/335/335-1736-mini.jpg","http://www.vegguide.org/entry-images/335/335-1736-small.jpg","http://www.vegguide.org/entry-images/335/335-1736-large.jpg","http://www.vegguide.org/entry-images/335/335-1736-original.jpg"]}
,{"name":"Molly Moon's Homemade Ice Cream","short_description":"Popular ice cream shop","price_range":"$ - inexpensive","veg_level_description":"Vegan-Friendly","website":"http://www.mollymoonicecream.com","address":"1408 34th Ave, Seattle, WA 98122","images":[]}
,{"name":"Caffe Fiore","short_description":"Organic coffee house with vegan pastries","price_range":"$$ - average","veg_level_description":"Vegan-Friendly","website":"http://www.caffefiore.com","phone":"206-282-1441","address":"224 W. Galer St., Seattle, Washington 98119","images":[]}
,{"name":"Eat Local","short_description":"Locavore store and restaurant with vegan options","price_range":"$$ - average","veg_level_description":"Vegan-Friendly","website":"http://www.eatlocalonline.com","phone":"206-328-3663","address":"2400 Queen Anne Avenue N., Seattle, WA 98109","images":[]}
,{"name":"Lucky Palate Vegetarian Meal Service","short_description":"provide weekly delivery of \"Heat and Serve\" meals to homes and businesses throughout the Seattle area","price_range":"$ - inexpensive","veg_level_description":"Vegetarian","website":"http://www.luckypalate.com","phone":"206.352.2583","address":"307 W. McGraw Street, Seattle, Washington 98119","images":["http://www.vegguide.org/entry-images/3228/3228-1652-mini.gif","http://www.vegguide.org/entry-images/3228/3228-1652-small.gif","http://www.vegguide.org/entry-images/3228/3228-1652-large.gif","http://www.vegguide.org/entry-images/3228/3228-1652-original.gif"]}
,{"name":"spud! Seattle","short_description":"Organic grocery deliveries","price_range":"$$ - average","veg_level_description":"Vegan-Friendly","website":"http://www.spud.com","phone":"206-621-7783","address":"8 South Idaho Street, Seattle, WA 98134","images":[]}
,{"name":"Tawon Thai","short_description":"Thai restaurant in the Fremont neighborhood.","price_range":"$$ - average","veg_level_description":"Vegan-Friendly","website":"http://www.tawonthai.com","phone":"(206) 633-4545","address":"3410 Fremont Ave N, Seattle, Washington 98103","images":[]}
,{"name":"Flying Apron Bakery","short_description":"Organic vegan bakery","price_range":"$ - inexpensive","veg_level_description":"Vegetarian","website":"http://www.flyingapron.net","phone":"206-442-1115","address":"3510 Fremont Avenue N, Seattle, WA 98103","images":[]}
,{"name":"PCC Natural Market","short_description":"Natural Foods Market","price_range":"$$ - average","veg_level_description":"Vegan-Friendly","website":"http://www.pugetcoop.com","phone":"206-937-8481","address":"2749 California Ave. SW, Seattle, Washington 98116","images":["http://www.vegguide.org/entry-images/1649/1649-551-mini.jpg","http://www.vegguide.org/entry-images/1649/1649-551-small.jpg","http://www.vegguide.org/entry-images/1649/1649-551-large.jpg","http://www.vegguide.org/entry-images/1649/1649-551-original.jpg"]}];